Repository DFE-Digital/npq-registration, pull requests merged in 2024-08, with the labels that each got.

#1566 [CPDLP-3350] Review nullable values in swagger docs
  public/api/docs/v1/swagger.yaml
  public/api/docs/v2/swagger.yaml
  public/api/docs/v3/swagger.yaml
  spec/swagger_schemas/requests/application_change_funded_place_request.rb
  spec/swagger_schemas/requests/participant_declaration_completed_request.rb
  spec/swagger_schemas/requests/participant_declaration_retained_request.rb
  spec/swagger_schemas/requests/participant_declaration_started_request.rb
Labels: separation

#1558 [CPDLP-3349] Add accepted at date field to applications
  app/serializers/api/participant_serializer.rb
  app/services/applications/accept.rb
  app/services/participants/query.rb
  db/migrate/20240725102353_add_accepted_at_to_applications.rb
  db/schema.rb
  spec/factories/applications.rb
  spec/features/journeys/happy_paths/able_to_receive_targeted_delivery_funding_spec.rb
  spec/features/journeys/happy_paths/basic_registration_journey_spec.rb
  spec/features/journeys/happy_paths/changing_do_you_work_in_a_school_from_no_to_yes_spec.rb
  spec/features/journeys/happy_paths/changing_do_you_work_in_childcare_from_yes_to_no_spec.rb
  spec/features/journeys/happy_paths/changing_from_outside_of_catchment_area_to_inside_spec.rb
  spec/features/journeys/happy_paths/changing_npq_to_one_leadprovider_no_longer_supports_spec.rb
  spec/features/journeys/happy_paths/funded_ehco_registration_journey_spec.rb
  spec/features/journeys/happy_paths/international_teacher_npqh_journey_spec.rb
  spec/features/journeys/happy_paths/other_funded_ehco_registration_journey_spec.rb
  spec/features/journeys/happy_paths/previously_received_targeted_delivery_funding_spec.rb
  spec/features/journeys/happy_paths/via_using_old_name_and_not_headship_spec.rb
  spec/features/journeys/happy_paths/via_using_same_name_spec.rb
  spec/features/journeys/happy_paths/when_choose_lead_mentor_course_spec.rb
  spec/features/journeys/happy_paths/when_choose_maths_course_spec.rb
  spec/features/journeys/happy_paths/when_get_an_identity_returns_no_trn_spec.rb
  spec/features/journeys/happy_paths/when_outside_of_catchment_area_crown_dependencies_spec.rb
  spec/features/journeys/happy_paths/when_outside_of_catchment_area_spec.rb
  spec/features/journeys/happy_paths/when_previously_funded_spec.rb
  spec/features/journeys/happy_paths/when_working_at_an_eligible_primary_school_spec.rb
  spec/features/journeys/happy_paths/while_not_currently_working_at_school_spec.rb
  spec/features/journeys/happy_paths/while_working_at_private_childcare_provider_but_not_a_nursery_spec.rb
  spec/features/journeys/happy_paths/while_working_at_private_nursery_spec.rb
  spec/features/journeys/happy_paths/while_working_at_public_nursery_spec.rb
  spec/features/journeys/happy_paths/while_working_in_neither_a_school_nor_childcare_spec.rb
  spec/features/journeys/sad_paths/applying_for_ehco_but_not_new_headteacher_spec.rb
  spec/features/journeys/sad_paths/lead_mentor_journey_with_incorrect_course_spec.rb
  spec/features/journeys/sad_paths/works_in_childcare_but_not_in_england_spec.rb
  spec/lib/services/handle_submission_for_store_spec.rb
  spec/serializers/api/applications_csv_serializer_spec.rb
  spec/serializers/api/participant_serializer_spec.rb
  spec/services/applications/accept_spec.rb
  spec/services/participants/query_spec.rb
Labels: separation

#1564 [CPDLP-3345] Remove unused request params before calling participant action services
  app/controllers/api/v1/participants_controller.rb
  app/controllers/api/v2/participants_controller.rb
  app/controllers/api/v3/participants_controller.rb
  app/services/participants/action.rb
  spec/support/shared_examples/api_update_endpoint_support.rb
  spec/support/shared_examples/participant_action_support.rb
Labels: separation

#1542 [CPDLP-3235] Enable sentry on separation env
  app/models/application.rb
  app/models/external/ecf_api/base.rb
  app/models/user.rb
  app/services/ecf/base.rb
  app/services/ecf/ecf_application_synchronization.rb
  app/services/ecf/ecf_user_creator.rb
  app/services/ecf/ecf_user_finder.rb
  app/services/ecf/ecf_user_updater.rb
  app/services/ecf/npq_profile_creator.rb
  app/services/ecf/npq_profile_mass_updater.rb
  app/services/ecf/npq_profile_updater.rb
  app/services/ecf/tsf_mass_data_field_updater.rb
  app/services/funding_eligibility.rb
  app/services/participant_validator.rb
  config/environments/development.rb
  config/environments/migration.rb
  config/environments/production.rb
  config/environments/review.rb
  config/environments/sandbox.rb
  config/environments/separation.rb
  config/environments/staging.rb
  config/environments/test.rb
  config/initializers/sentry.rb
  docs/merging_deployment_and_env_variables.md
  spec/lib/services/ecf/ecf_application_synchronization_spec.rb
  spec/lib/services/ecf/ecf_user_creator_spec.rb
  spec/lib/services/ecf/ecf_user_finder_spec.rb
  spec/lib/services/ecf/ecf_user_updater_spec.rb
  spec/lib/services/ecf/npq_profile_creator_spec.rb
  spec/lib/services/ecf/npq_profile_mass_updater_spec.rb
  spec/lib/services/ecf/npq_profile_updater_spec.rb
  spec/lib/services/ecf/tsf_mass_data_field_updater_spec.rb
  spec/lib/services/funding_eligibility_spec.rb
  spec/lib/services/participant_validator_spec.rb
  spec/models/application_spec.rb
  spec/models/user_spec.rb
  terraform/application/config/separation.tfvars.json
Labels: separation

#1580 Add release note for NPQ MVP release
  app/models/release_notes.rb
  app/views/api/guidance/release-notes.md
  release-notes.md
Labels: DO NOT MERGE

#1585 [CPDLP-3391] Only surface accepted applications in enrolments
  app/serializers/api/participant_serializer.rb
  spec/serializers/api/participant_serializer_spec.rb
Labels: separation

#1388 API guidance updates
  app/components/npq_separation/navigation_structures/guidance_navigation_structure.rb
  app/views/api/guidance/api-latest-version.md
  app/views/api/guidance/data-states.md
  app/views/api/guidance/definitions.md
  app/views/api/guidance/get-started.md
  app/views/api/guidance/how-npqs-work.md
  app/views/api/guidance/index.html.erb
  app/views/api/guidance/release-notes.md
  app/views/api/guidance/schedules-and-milestone-dates.md
  app/views/api/guidance/submit-view-and-void-declarations.md
  app/views/api/guidance/test-environment.md
  app/views/api/guidance/test-environments.md
  app/views/api/guidance/test.md
  app/views/api/guidance/view-accept-or-reject-applications.md
  app/views/api/guidance/view-and-update-participant-data.md
  app/views/api/guidance/view-payments-information.md
  app/views/api/guidance/what-you-can-do-in-the-api.md
  app/views/layouts/api_docs.html.erb
  app/views/layouts/api_guidance.html.erb
  app/views/layouts/api_guidance/_header.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/shared/_govuk_javascript.html.erb
  app/webpacker/styles/api_guidance.scss
  app/webpacker/styles/application.scss
  app/webpacker/styles/code.scss
  spec/components/npq_separation/navigation_structures/guidance_navigation_structure_spec.rb
  spec/features/guidance_spec.rb
Labels: separation

#1571 [CPDLP-3292] Stream API requests events to BQ
  app/jobs/stream_api_requests_to_big_query_job.rb
  config/application.rb
  config/initializers/google_big_query.rb
  lib/middleware/api_request_middleware.rb
  spec/jobs/stream_api_requests_to_big_query_job_spec.rb
  spec/lib/middleware/api_request_middleware_spec.rb
Labels: separation

#1623 Upgrade terraform azurerm providers to 3.116.0
  .gitignore
  terraform/application/.terraform.lock.hcl
  terraform/application/database.tf
  terraform/application/terraform.tf
  terraform/domains/environment_domains/.terraform.lock.hcl
  terraform/domains/environment_domains/terraform.tf
  terraform/domains/infrastructure/.terraform.lock.hcl
  terraform/domains/infrastructure/terraform.tf
Labels: devops

#1624 [CPDLP-3442] Add new table and model for outcomes api request
  app/models/participant_outcome.rb
  app/models/participant_outcome_api_request.rb
  db/migrate/20240820153944_create_participant_outcome_api_requests.rb
  db/schema.rb
  spec/factories/participant_outcome_api_requests.rb
  spec/models/participant_outcome_api_request_spec.rb
  spec/models/participant_outcome_spec.rb
Labels: separation

#1637 Add snyk scan to build workflow
  .github/actions/build-and-push-docker-image/action.yml
  .github/workflows/deploy.yml
Labels: devops

#1634 [CPDLP-3443] Add QualifiedTeachersApiSender and QualifiedTeachers::Client
  .env.template
  .env.test
  app/models/course.rb
  app/services/qualified_teachers_api_sender.rb
  config/locales/en.yml
  lib/qualified_teachers.rb
  lib/qualified_teachers/client.rb
  spec/lib/qualified_teachers/client_spec.rb
  spec/models/course_spec.rb
  spec/services/qualified_teachers_api_sender_spec.rb
Labels: separation

#1645 [CPDLP-3444] Add BatchSendLatestOutcomesJob and SendToQualifiedTeachersApiJob
  app/jobs/crons/batch_send_latest_outcomes_job.rb
  app/jobs/send_to_qualified_teachers_api_job.rb
  app/models/participant_outcome.rb
  app/services/qualified_teachers_api_sender.rb
  config/initializers/delayed_job.rb
  spec/factories/participant_outcomes.rb
  spec/jobs/crons/batch_send_latest_outcomes_job_spec.rb
  spec/jobs/send_to_qualified_teachers_api_job_spec.rb
  spec/models/participant_outcome_spec.rb
Labels: separation
